In [19]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit

In [20]:
df = pd.read_csv("housing.csv")

In [21]:
df['income_cat'] = pd.cut(df['median_income'], bins = [0, 1.5, 3.0, 4.5, 6.0, 7.5, np.inf], labels = [1, 2, 3 ,4 ,5, 6 ])

In [22]:
split = StratifiedShuffleSplit(n_splits = 1, test_size = 0.2, random_state = 42)
for train_index, test_index in split.split(df, df['income_cat']):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

In [23]:
#Remove income_cat column
for x in (strat_train_set, strat_test_set):
    x.drop("income_cat", axis = 1, inplace = True)

In [24]:
strat_train_set.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
6895,-118.11,34.04,28.0,3913.0,696.0,2264.0,697.0,5.2446,258000.0,<1H OCEAN
2880,-118.97,35.38,35.0,1673.0,426.0,1041.0,413.0,1.3750,57500.0,INLAND
13769,-117.03,34.07,16.0,3784.0,577.0,1615.0,525.0,4.2333,220300.0,INLAND
18349,-122.17,37.43,24.0,3924.0,1142.0,7174.0,950.0,4.0972,387500.0,NEAR OCEAN
16188,-121.31,37.96,48.0,1112.0,227.0,583.0,216.0,2.3393,77600.0,INLAND

In [25]:
df = strat_train_set.copy()

In [26]:
housing = strat_train_set.drop("median_house_value", axis = 1)
housing_labels = strat_train_set["median_house_value"]

In [27]:
housing.describe()
#We can see there are missing values in total_bedrooms

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
count,16512.000000,16512.00000,16512.000000,16512.000000,16358.000000,16512.000000,16512.00000,16512.000000
mean,-119.572346,35.63674,28.628513,2628.114583,535.663529,1422.758600,497.75327,3.873473
std,2.001511,2.13778,12.586026,2157.526589,413.333152,1120.859666,376.32796,1.900464
min,-124.350000,32.54000,1.000000,6.000000,1.000000,3.000000,1.00000,0.499900
25%,-121.800000,33.93000,18.000000,1445.000000,295.000000,786.000000,279.00000,2.566775
50%,-118.510000,34.26000,29.000000,2123.500000,433.500000,1166.000000,408.00000,3.540900
75%,-118.010000,37.72000,37.000000,3143.250000,645.000000,1720.000000,603.00000,4.744475
max,-114.310000,41.95000,52.000000,39320.000000,6210.000000,35682.000000,5358.00000,15.000100

In [28]:
from sklearn.impute import SimpleImputer

In [29]:
imputer = SimpleImputer(strategy = "median")

In [30]:
housing_num = housing.select_dtypes(include = [np.number])
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [36]:
X = imputer.transform(housing_num)#X is transformed into numpy arrsay
housing_br = pd.DataFrame(X, columns = housing_num.columns, index = housing_num.index)
# To transform X again into Pandas Data

In [37]:
housing_br.describe()
#The missing values of toatl_bedrooms

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
count,16512.000000,16512.00000,16512.000000,16512.000000,16512.000000,16512.000000,16512.00000,16512.000000
mean,-119.572346,35.63674,28.628513,2628.114583,534.710695,1422.758600,497.75327,3.873473
std,2.001511,2.13778,12.586026,2157.526589,411.518229,1120.859666,376.32796,1.900464
min,-124.350000,32.54000,1.000000,6.000000,1.000000,3.000000,1.00000,0.499900
25%,-121.800000,33.93000,18.000000,1445.000000,297.000000,786.000000,279.00000,2.566775
50%,-118.510000,34.26000,29.000000,2123.500000,433.500000,1166.000000,408.00000,3.540900
75%,-118.010000,37.72000,37.000000,3143.250000,642.000000,1720.000000,603.00000,4.744475
max,-114.310000,41.95000,52.000000,39320.000000,6210.000000,35682.000000,5358.00000,15.000100