In [266]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit

In [267]:
df = pd.read_csv("housing.csv")

In [268]:
df['income_cat'] = pd.cut(df['median_income'], bins = [0, 1.5, 3.0, 4.5, 6.0, 7.5, np.inf], labels = [1, 2, 3 ,4 ,5, 6 ])

In [269]:
split = StratifiedShuffleSplit(n_splits = 1, test_size = 0.2, random_state = 42)
for train_index, test_index in split.split(df, df['income_cat']):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

In [270]:
#Remove income_cat column
for x in (strat_train_set, strat_test_set, df):
    x.drop("income_cat", axis = 1, inplace = True)

In [271]:
strat_train_set.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
6895,-118.11,34.04,28.0,3913.0,696.0,2264.0,697.0,5.2446,258000.0,<1H OCEAN
2880,-118.97,35.38,35.0,1673.0,426.0,1041.0,413.0,1.3750,57500.0,INLAND
13769,-117.03,34.07,16.0,3784.0,577.0,1615.0,525.0,4.2333,220300.0,INLAND
18349,-122.17,37.43,24.0,3924.0,1142.0,7174.0,950.0,4.0972,387500.0,NEAR OCEAN
16188,-121.31,37.96,48.0,1112.0,227.0,583.0,216.0,2.3393,77600.0,INLAND

In [272]:
housing = strat_train_set.drop("median_house_value", axis = 1)
housing_labels = strat_train_set["median_house_value"]

In [273]:
from sklearn.impute import SimpleImputer

In [274]:
imputer = SimpleImputer(strategy = "median")

In [275]:
housing_num = housing.select_dtypes(include = [np.number])
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [276]:
X = imputer.transform(housing_num)#X is transformed into numpy arrsay
housing = pd.DataFrame(X, columns = housing_num.columns, index = housing_num.index)
# To transform X again into Pandas Data

In [277]:
housing.head()
#The missing values of toatal_bedrooms is filled

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
6895,-118.11,34.04,28.0,3913.0,696.0,2264.0,697.0,5.2446
2880,-118.97,35.38,35.0,1673.0,426.0,1041.0,413.0,1.3750
13769,-117.03,34.07,16.0,3784.0,577.0,1615.0,525.0,4.2333
18349,-122.17,37.43,24.0,3924.0,1142.0,7174.0,950.0,4.0972
16188,-121.31,37.96,48.0,1112.0,227.0,583.0,216.0,2.3393

In [278]:
housing['ocean_proximity'] = df['ocean_proximity']

In [279]:
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
6895,-118.11,34.04,28.0,3913.0,696.0,2264.0,697.0,5.2446,<1H OCEAN
2880,-118.97,35.38,35.0,1673.0,426.0,1041.0,413.0,1.3750,INLAND
13769,-117.03,34.07,16.0,3784.0,577.0,1615.0,525.0,4.2333,INLAND
18349,-122.17,37.43,24.0,3924.0,1142.0,7174.0,950.0,4.0972,NEAR OCEAN
16188,-121.31,37.96,48.0,1112.0,227.0,583.0,216.0,2.3393,INLAND
...,...,...,...,...,...,...,...,...,...
10505,-117.72,33.43,5.0,1889.0,359.0,616.0,246.0,3.8992,<1H OCEAN
19526,-120.97,37.65,16.0,3960.0,716.0,1776.0,724.0,3.9886,INLAND
9347,-122.58,37.98,52.0,1180.0,216.0,467.0,197.0,4.9615,NEAR BAY
3650,-118.44,34.21,37.0,1665.0,335.0,1011.0,343.0,4.8703,<1H OCEAN
15088,-116.91,32.81,22.0,4331.0,637.0,1952.0,654.0,5.4834,<1H OCEAN

In [280]:
house1 = housing.copy()
house2 = housing[['ocean_proximity']]#In One hot encoder we will only work with this columns

In [281]:
from sklearn.preprocessing import OrdinalEncoder

In [282]:
ordinalencoder = OrdinalEncoder()
housing_cat1 = ordinalencoder.fit_transform(house1)

In [283]:
house1 = pd.DataFrame(housing_cat1, columns = house1.columns, index = house1.index)

In [284]:
house1
# !! here problem is ML can learn that 00 is far from 04 and closer to 01 which can lead to errors

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
6895,574.0,150.0,27.0,3591.0,696.0,2192.0,696.0,8110.0,0.0
2880,488.0,274.0,34.0,1467.0,425.0,1001.0,412.0,369.0,1.0
13769,682.0,153.0,15.0,3484.0,577.0,1575.0,524.0,6489.0,1.0
18349,168.0,461.0,23.0,3598.0,1130.0,3542.0,948.0,6193.0,4.0
16188,254.0,514.0,47.0,909.0,226.0,543.0,215.0,2221.0,1.0
...,...,...,...,...,...,...,...,...,...
10505,613.0,89.0,4.0,1683.0,358.0,576.0,245.0,5791.0,0.0
19526,288.0,483.0,15.0,3623.0,716.0,1735.0,723.0,5943.0,1.0
9347,127.0,516.0,51.0,974.0,215.0,427.0,196.0,7562.0,3.0
3650,541.0,167.0,36.0,1459.0,334.0,971.0,342.0,7464.0,0.0
15088,694.0,27.0,21.0,3896.0,637.0,1905.0,653.0,8494.0,0.0

In [285]:
from sklearn.preprocessing import OneHotEncoder

In [291]:
onehotencoder = OneHotEncoder()
housing_cat2 = onehotencoder.fit_transform(house2)

In [293]:
onehotencoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [297]:
house2 = pd.DataFrame(housing_cat2.toarray(), columns = ['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'], index = house2.index)

In [298]:
house2

       <1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
6895         1.0     0.0     0.0       0.0         0.0
2880         0.0     1.0     0.0       0.0         0.0
13769        0.0     1.0     0.0       0.0         0.0
18349        0.0     0.0     0.0       0.0         1.0
16188        0.0     1.0     0.0       0.0         0.0
...          ...     ...     ...       ...         ...
10505        1.0     0.0     0.0       0.0         0.0
19526        0.0     1.0     0.0       0.0         0.0
9347         0.0     0.0     0.0       1.0         0.0
3650         1.0     0.0     0.0       0.0         0.0
15088        1.0     0.0     0.0       0.0         0.0

[16512 rows x 5 columns]