In [69]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit

In [70]:
df = pd.read_csv("housing.csv")

In [71]:
df['income_cat'] = pd.cut(df['median_income'], bins = [0, 1.5, 3.0, 4.5, 6.0, 7.5, np.inf], labels = [1, 2, 3 ,4 ,5, 6 ])

In [72]:
split = StratifiedShuffleSplit(n_splits = 1, test_size = 0.2, random_state = 42)
for train_index, test_index in split.split(df, df['income_cat']):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

In [73]:
#Remove income_cat column
for x in (strat_train_set, strat_test_set, df):
    x.drop("income_cat", axis = 1, inplace = True)

In [74]:
df = strat_train_set.copy()

In [75]:
housing = strat_train_set.drop("median_house_value", axis = 1)
housing_labels = strat_train_set["median_house_value"].copy

In [76]:
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
6895,-118.11,34.04,28.0,3913.0,696.0,2264.0,697.0,5.2446,<1H OCEAN
2880,-118.97,35.38,35.0,1673.0,426.0,1041.0,413.0,1.3750,INLAND
13769,-117.03,34.07,16.0,3784.0,577.0,1615.0,525.0,4.2333,INLAND
18349,-122.17,37.43,24.0,3924.0,1142.0,7174.0,950.0,4.0972,NEAR OCEAN
16188,-121.31,37.96,48.0,1112.0,227.0,583.0,216.0,2.3393,INLAND
...,...,...,...,...,...,...,...,...,...
10505,-117.72,33.43,5.0,1889.0,359.0,616.0,246.0,3.8992,<1H OCEAN
19526,-120.97,37.65,16.0,3960.0,716.0,1776.0,724.0,3.9886,INLAND
9347,-122.58,37.98,52.0,1180.0,216.0,467.0,197.0,4.9615,NEAR BAY
3650,-118.44,34.21,37.0,1665.0,335.0,1011.0,343.0,4.8703,<1H OCEAN
15088,-116.91,32.81,22.0,4331.0,637.0,1952.0,654.0,5.4834,<1H OCEAN

In [77]:
housing = housing.drop("ocean_proximity", axis = 1)

In [78]:
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

In [79]:
mypipeline = Pipeline([
             ("imputer", SimpleImputer(strategy="median")),
             ("Scaler", StandardScaler()),
              ])

In [80]:
housing_pip = mypipeline.fit_transform(housing)

In [82]:
housing = pd.DataFrame(housing_pip, columns = housing.columns, index = housing.index)

In [83]:
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
6895,0.730643,-0.746937,-0.049939,0.595554,0.391949,0.750555,0.529466,0.721492
2880,0.300955,-0.120100,0.506250,-0.442703,-0.264178,-0.340605,-0.225218,-1.314705
13769,1.270252,-0.732904,-1.003406,0.535762,0.102767,0.171518,0.072404,0.189342
18349,-1.297886,0.838867,-0.367761,0.600653,1.475773,5.131254,1.201772,0.117726
16188,-0.868198,1.086796,1.539173,-0.702731,-0.747768,-0.749232,-0.748713,-0.807287
...,...,...,...,...,...,...,...,...
10505,0.925502,-1.032289,-1.877418,-0.342585,-0.426994,-0.719790,-0.668993,0.013538
19526,-0.698321,0.941781,-1.003406,0.617339,0.440551,0.315162,0.601214,0.060580
9347,-1.502738,1.096151,1.856996,-0.671212,-0.774499,-0.852727,-0.799203,0.572524
3650,0.565763,-0.667413,0.665162,-0.446411,-0.485317,-0.367371,-0.411232,0.524534
15088,1.330208,-1.322318,-0.526672,0.789301,0.248573,0.472189,0.415200,0.847149